const dbName = 'book_library';

db = db.getSiblingDB(dbName);

db.createUser({
  user: 'node_user',
  pwd: 'node_user_password',
  roles: [
    {
      role: 'readWrite',
      db: dbName,
    },
  ],
});

db.createCollection('books');

const seedData = [
  {
    isbn: '9780140328721',
    title: 'Matilda',
    author: 'Roald Dahl',
    status: 'available',
  },
  {
    isbn: '9780140328721',
    title: 'Matilda',
    author: 'Roald Dahl',
    status: 'available',
  },
  {
    isbn: '9780140328721',
    title: 'Matilda',
    author: 'Roald Dahl',
    status: 'available',
  },
  {
    isbn: '9780140328721',
    title: 'Matilda',
    author: 'Roald Dahl',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780439554930',
    title: "Harry Potter and the Sorcerer's Stone",
    author: 'J.K. Rowling',
    status: 'checked-out',
  },
  {
    isbn: '9780439554930',
    title: "Harry Potter and the Sorcerer's Stone",
    author: 'J.K. Rowling',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780061122415',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    status: 'available',
  },
  {
    isbn: '9780061122415',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780743273565',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    status: 'checked-out',
  },
  {
    isbn: '9780743273565',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    status: 'checked-out',
  },
  {
    isbn: '9780743273565',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780679783268',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    status: 'available',
  },
  {
    isbn: '9780679783268',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    status: 'checked-out',
  },
  {
    isbn: '9780679783268',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780451524935',
    title: '1984',
    author: 'George Orwell',
    status: 'available',
  },
  {
    isbn: '9780451524935',
    title: '1984',
    author: 'George Orwell',
    status: 'available',
  },
  {
    isbn: '9780451524935',
    title: '1984',
    author: 'George Orwell',
    status: 'available',
  },
  {
    isbn: '9780451524935',
    title: '1984',
    author: 'George Orwell',
    status: 'checked-out',
  },
  {
    isbn: '9780451524935',
    title: '1984',
    author: 'George Orwell',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780316769488',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    status: 'checked-out',
  },
  {
    isbn: '9780316769488',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    status: 'available',
  },
  {
    isbn: '9780316769488',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    status: 'available',
  },
  {
    isbn: '9780316769488',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9781501128034',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    status: 'available',
  },
  {
    isbn: '9780141439518',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    status: 'available',
  },
  {
    isbn: '9780141439518',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    status: 'available',
  },
  {
    isbn: '9780141439518',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780140449266',
    title: 'Les Misérables',
    author: 'Victor Hugo',
    status: 'checked-out',
  },
  {
    isbn: '9780743482837',
    title: 'Hamlet',
    author: 'William Shakespeare',
    status: 'available',
  },
  {
    isbn: '9780743482837',
    title: 'Hamlet',
    author: 'William Shakespeare',
    status: 'available',
  },
  {
    isbn: '9780743482837',
    title: 'Hamlet',
    author: 'William Shakespeare',
    status: 'checked-out',
  },
  {
    isbn: '9780743482837',
    title: 'Hamlet',
    author: 'William Shakespeare',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780553212419',
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    status: 'available',
  },
  {
    isbn: '9780553212419',
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    status: 'checked-out',
  },
  {
    isbn: '9780553212419',
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780486415864',
    title: 'Moby-Dick',
    author: 'Herman Melville',
    status: 'checked-out',
  },
  {
    isbn: '9780486275578',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    status: 'available',
  },
  {
    isbn: '9780486275578',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    status: 'available',
  },
  {
    isbn: '9780486275578',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    status: 'available',
  },
  {
    isbn: '9780486275578',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9781492636733',
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    status: 'available',
  },
  {
    isbn: '9781492636733',
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    status: 'available',
  },
  {
    isbn: '9781492636733',
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780140449112',
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    status: 'checked-out',
  },
  {
    isbn: '9780140449112',
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    status: 'checked-out',
  },
  {
    isbn: '9780140449112',
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9780140449242',
    title: 'The Odyssey',
    author: 'Homer',
    status: 'available',
  },
  {
    isbn: '9780486280619',
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    status: 'available',
  },
  {
    isbn: '9780486280619',
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    status: 'available',
  },
  {
    isbn: '9780486280619',
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9781593082069',
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    status: 'checked-out',
  },
  {
    isbn: '9781593082069',
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    status: 'checked-out',
  },
  {
    isbn: '9781593082069',
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    status: 'available',
    referenceBook: true,
  },
  {
    isbn: '9781614272777',
    title: 'The Republic',
    author: 'Plato',
    status: 'available',
  },
  {
    isbn: '9781614272777',
    title: 'The Republic',
    author: 'Plato',
    status: 'available',
    referenceBook: true,
  },
];

//? insert these books into the database
db.books.insertMany(seedData);
